[2023-11-20T08:43:30.533+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:43:30.538+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:43:30.539+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:30.545+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T08:43:30.550+0000] {standard_task_runner.py:57} INFO - Started process 191 to run task
[2023-11-20T08:43:30.553+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'load_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpgtv40qsj']
[2023-11-20T08:43:30.555+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask load_data
[2023-11-20T08:43:30.590+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:30.634+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T08:43:31.246+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 179, in load_data
    engine = create_engine(DATABASE_URL)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 794, in _parse_url
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '{}'
[2023-11-20T08:43:31.250+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=load_data, execution_date=20231114T000000, start_date=20231120T084330, end_date=20231120T084331
[2023-11-20T08:43:31.260+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task load_data (invalid literal for int() with base 10: '{}'; 191)
[2023-11-20T08:43:31.294+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:43:31.302+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:44.660+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:46:44.667+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:46:44.676+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:44.797+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T08:46:44.809+0000] {standard_task_runner.py:57} INFO - Started process 192 to run task
[2023-11-20T08:46:44.816+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'load_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp1bdaxueq']
[2023-11-20T08:46:44.828+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask load_data
[2023-11-20T08:46:44.969+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:45.076+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T08:46:47.868+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:47.880+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=load_data, execution_date=20231114T000000, start_date=20231120T084644, end_date=20231120T084647
[2023-11-20T08:46:47.923+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:47.946+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:24.328+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:50:24.347+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:50:24.347+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:24.365+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T08:50:24.371+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2023-11-20T08:50:24.381+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'load_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpbacd6uyg']
[2023-11-20T08:50:24.389+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask load_data
[2023-11-20T08:50:24.438+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:24.511+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T08:50:27.827+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:27.849+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=load_data, execution_date=20231114T000000, start_date=20231120T085024, end_date=20231120T085027
[2023-11-20T08:50:27.903+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:27.919+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
