[2023-11-20T08:43:30.024+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-20T08:43:30.042+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-20T08:43:30.045+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:30.113+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-11 00:00:00+00:00
[2023-11-20T08:43:30.120+0000] {standard_task_runner.py:57} INFO - Started process 181 to run task
[2023-11-20T08:43:30.126+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'load_data', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpbr7vjg2g']
[2023-11-20T08:43:30.141+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask load_data
[2023-11-20T08:43:30.213+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:30.290+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-20T08:43:30.923+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 179, in load_data
    engine = create_engine(DATABASE_URL)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 794, in _parse_url
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '{}'
[2023-11-20T08:43:30.930+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=load_data, execution_date=20231111T000000, start_date=20231120T084330, end_date=20231120T084330
[2023-11-20T08:43:30.936+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task load_data (invalid literal for int() with base 10: '{}'; 181)
[2023-11-20T08:43:30.944+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:43:30.955+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:45.335+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-20T08:46:45.344+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-20T08:46:45.345+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:45.355+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-11 00:00:00+00:00
[2023-11-20T08:46:45.360+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2023-11-20T08:46:45.364+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'load_data', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpctvddeu_']
[2023-11-20T08:46:45.369+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask load_data
[2023-11-20T08:46:45.421+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:45.483+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-20T08:46:48.322+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:48.329+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=load_data, execution_date=20231111T000000, start_date=20231120T084645, end_date=20231120T084648
[2023-11-20T08:46:48.367+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:48.379+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:23.747+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-20T08:50:23.761+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-20T08:50:23.762+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:23.789+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-11 00:00:00+00:00
[2023-11-20T08:50:23.800+0000] {standard_task_runner.py:57} INFO - Started process 176 to run task
[2023-11-20T08:50:23.808+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'load_data', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpfas_bxsb']
[2023-11-20T08:50:23.814+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask load_data
[2023-11-20T08:50:23.917+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.load_data scheduled__2023-11-11T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:24.028+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-20T08:50:27.173+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:27.186+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=load_data, execution_date=20231111T000000, start_date=20231120T085023, end_date=20231120T085027
[2023-11-20T08:50:27.235+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:27.253+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
